services:
  traefik:
    image: traefik:v3.0.1
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --providers.swarm.endpoint="unix:///var/run/docker.sock"
      - --providers.swarm.exposedByDefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik-public
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 10s

networks:
  traefik-public:
    driver: overlay