services:
  traefik:
    image: 127.0.0.1:8082/repository/docker-hosted/traefik-test:latest
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-public
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 10s

networks:
  traefik-public:
    driver: overlay