[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"

[providers]
  [providers.swarm]
    endpoint = "unix:///var/run/docker.sock"
    exposedByDefault = false

[api]
  dashboard = true
  insecure = true
