[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"

[providers]
  [providers.swarm]
    endpoint = "tcp://127.0.0.1:2377"
    exposedByDefault = false

[api]
  dashboard = true
  insecure = true
